# Generated by Django 3.2 on 2021-04-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.IntegerField(max_length=11)),
                ('password', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('targetColleges', models.CharField(blank=True, max_length=255, null=True)),
                ('targetScore', models.IntegerField(blank=True, null=True)),
                ('currentScore', models.IntegerField(blank=True, null=True)),
                ('historyScore', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
