# Generated by Django 3.2 on 2021-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateUser',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='id,唯一标识')),
                ('username', models.CharField(max_length=11, verbose_name='用户名,登陆用')),
                ('password', models.CharField(max_length=11, verbose_name='密码')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
                ('targetCollege', models.CharField(blank=True, max_length=255, verbose_name='目标院校')),
                ('targetScore', models.IntegerField(blank=True, verbose_name='理想成绩')),
                ('currentScore', models.IntegerField(blank=True, verbose_name='当前成绩')),
                ('historyScore', models.IntegerField(blank=True, verbose_name='历史成绩')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
