# Generated by Django 3.2 on 2021-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False, verbose_name='年份')),
                ('bk1', models.FloatField(verbose_name='一本线')),
                ('bk2', models.FloatField(verbose_name='二本线')),
                ('bk3', models.FloatField(verbose_name='三本线')),
                ('isAnalysis', models.BooleanField(blank=True, default=False, verbose_name='是否预测值')),
            ],
            options={
                'db_table': 'zhejiang',
            },
        ),
    ]
