# Generated by Django 3.2 on 2021-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eighteen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='院校id')),
                ('college', models.CharField(max_length=255, verbose_name='院校名字')),
                ('grade', models.IntegerField(verbose_name='分数线')),
                ('ranking', models.IntegerField(verbose_name='排位')),
            ],
            options={
                'db_table': '2018',
            },
        ),
        migrations.CreateModel(
            name='Nineteen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='院校id')),
                ('college', models.CharField(max_length=255, verbose_name='院校名字')),
                ('grade', models.IntegerField(verbose_name='分数线')),
                ('ranking', models.IntegerField(verbose_name='排位')),
            ],
            options={
                'db_table': '2019',
            },
        ),
        migrations.CreateModel(
            name='Seventeen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='院校id')),
                ('college', models.CharField(max_length=255, verbose_name='院校名字')),
                ('grade', models.IntegerField(verbose_name='分数线')),
                ('ranking', models.IntegerField(verbose_name='排位')),
            ],
            options={
                'db_table': '2017',
            },
        ),
        migrations.CreateModel(
            name='Twenty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='院校id')),
                ('college', models.CharField(max_length=255, verbose_name='院校名字')),
                ('grade', models.IntegerField(verbose_name='分数线')),
                ('ranking', models.IntegerField(verbose_name='排位')),
            ],
            options={
                'db_table': '2020',
            },
        ),
    ]
